# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GTFSshapesTracer
                                 A QGIS plugin
 It transforms the Public Transport paths in GTFS Shapes.txt
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-06
        copyright            : (C) 2024 by Luigi
        email                : luigi.dalbosco@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GTFSshapesTracer class from file GTFSshapesTracer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GTFS_shapes_Tracer import GTFSshapesTracer
    return GTFSshapesTracer(iface)
